
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/maze
    username:
    password:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false


